# ReplicaSet para 3 replicas
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-replica-set
spec:
  replicas: 3
  selector:
    matchLabels:
      type: web-app
  template:
    metadata:
      labels:
        type: web-app
    spec:
      containers:
        - name: web-server-apache
          image: httpd
          ports:
            - containerPort: 80
        - name: web-server-tomcat
          image: tomcat
          ports:
            - containerPort: 8080
--- 
# Service para externalname
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-externalname
spec:
  type: ExternalName
  externalName: www.google.com
  ports:
    - name: http
      port: 80
      targetPort: 80